name: gemarbaca_petugas
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  get: 4.6.6
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_do: ^3.1.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
  web:
    generate: true
    image_path: "assets/image/logo.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
  fonts:
    - family: Alegreya
      fonts:
        - asset: assets/font/Alegreya-Bold.ttf
          weight: 700
        - asset: assets/font/Alegreya-Regular.ttf